<a href="https://colab.research.google.com/github/nadjakencana/2025_Kecerdasan_Buatan_TI1b/blob/main/Fix_Latihan_Data_Manipulation_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# LATIHAN

## Import Library

In [1]:
import pandas as pd

## Load Dataset

In [2]:
df = pd.read_csv('./Data.csv')
df

     Negara    Umur        Gaji Transaksi
0   Jakarta    44.0   8000000.0     Tidak
1   Bandung    27.0   6500000.0        Ya
2  Surabaya    30.0   4500000.0     Tidak
3   Bandung    38.0   7500000.0     Tidak
4  Surabaya    40.0         NaN        Ya
5   Jakarta    35.0  10000000.0        Ya
6   Bandung     NaN   8250000.0     Tidak
7   Jakarta    48.0   9750000.0        Ya
8  Surabaya  1000.0   7674000.0     Tidak
9   Jakarta    37.0   6700000.0        Ya

In [3]:
df.isnull().sum()

Negara       0
Umur         1
Gaji         1
Transaksi    0
dtype: int64

## Mengatasi Missing Values dengan Drop Data

### 1. Hapus Data yang kosong (NaN)

In [4]:
df = pd.read_csv('./Data.csv')
df.dropna(inplace=True)

df

     Negara    Umur        Gaji Transaksi
0   Jakarta    44.0   8000000.0     Tidak
1   Bandung    27.0   6500000.0        Ya
2  Surabaya    30.0   4500000.0     Tidak
3   Bandung    38.0   7500000.0     Tidak
5   Jakarta    35.0  10000000.0        Ya
7   Jakarta    48.0   9750000.0        Ya
8  Surabaya  1000.0   7674000.0     Tidak
9   Jakarta    37.0   6700000.0        Ya

## Mengatasi Missing Values dengan Nilai Baru

### 2. Ganti Data yang kosong (NaN) menjadi :

### <ul><li>Umur = 50 </li><li>Gaji = 25000000</li></ul>

In [5]:
df = pd.read_csv('./Data.csv')
df['Umur'].fillna(50, inplace=True)
df['Gaji'].fillna(25000000, inplace=True)
df

<ipython-input-5-cefa89afd30c>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Umur'].fillna(50, inplace=True)
<ipython-input-5-cefa89afd30c>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Gaji'].fillna(25000000, inplace=True)

     Negara    Umur        Gaji Transaksi
0   Jakarta    44.0   8000000.0     Tidak
1   Bandung    27.0   6500000.0        Ya
2  Surabaya    30.0   4500000.0     Tidak
3   Bandung    38.0   7500000.0     Tidak
4  Surabaya    40.0  25000000.0        Ya
5   Jakarta    35.0  10000000.0        Ya
6   Bandung    50.0   8250000.0     Tidak
7   Jakarta    48.0   9750000.0        Ya
8  Surabaya  1000.0   7674000.0     Tidak
9   Jakarta    37.0   6700000.0        Ya

In [6]:
df

     Negara    Umur        Gaji Transaksi
0   Jakarta    44.0   8000000.0     Tidak
1   Bandung    27.0   6500000.0        Ya
2  Surabaya    30.0   4500000.0     Tidak
3   Bandung    38.0   7500000.0     Tidak
4  Surabaya    40.0  25000000.0        Ya
5   Jakarta    35.0  10000000.0        Ya
6   Bandung    50.0   8250000.0     Tidak
7   Jakarta    48.0   9750000.0        Ya
8  Surabaya  1000.0   7674000.0     Tidak
9   Jakarta    37.0   6700000.0        Ya

## Mengatasi Missing Values dengan Nilai Mean

## 3. Ganti Data Kosong (NaN) pada Umur dan Gaji dengan Nilai Rata-Rata

In [7]:
df = pd.read_csv('./Data.csv')
mean_umur = df['Umur'].mean();
mean_gaji = df['Gaji'].mean();

df['Umur'].fillna(mean_umur, inplace=True)
df['Gaji'].fillna(mean_gaji, inplace=True)
df

<ipython-input-7-6b88f0aebe06>:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Umur'].fillna(mean_umur, inplace=True)
<ipython-input-7-6b88f0aebe06>:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Gaji'].fillna(mean_gaji, inplace=True)

     Negara         Umur          Gaji Transaksi
0   Jakarta    44.000000  8.000000e+06     Tidak
1   Bandung    27.000000  6.500000e+06        Ya
2  Surabaya    30.000000  4.500000e+06     Tidak
3   Bandung    38.000000  7.500000e+06     Tidak
4  Surabaya    40.000000  7.652667e+06        Ya
5   Jakarta    35.000000  1.000000e+07        Ya
6   Bandung   144.333333  8.250000e+06     Tidak
7   Jakarta    48.000000  9.750000e+06        Ya
8  Surabaya  1000.000000  7.674000e+06     Tidak
9   Jakarta    37.000000  6.700000e+06        Ya

In [8]:
df

     Negara         Umur          Gaji Transaksi
0   Jakarta    44.000000  8.000000e+06     Tidak
1   Bandung    27.000000  6.500000e+06        Ya
2  Surabaya    30.000000  4.500000e+06     Tidak
3   Bandung    38.000000  7.500000e+06     Tidak
4  Surabaya    40.000000  7.652667e+06        Ya
5   Jakarta    35.000000  1.000000e+07        Ya
6   Bandung   144.333333  8.250000e+06     Tidak
7   Jakarta    48.000000  9.750000e+06        Ya
8  Surabaya  1000.000000  7.674000e+06     Tidak
9   Jakarta    37.000000  6.700000e+06        Ya

## Mengatasi Missing Values dengan Nilai Median

## 4. Ganti Data Kosong (NaN) pada Umur dan Gaji dengan Nilai Median

In [9]:
df = pd.read_csv('./Data.csv')
mean_umur = df['Umur'].median();
mean_gaji = df['Gaji'].median();

df['Umur'].fillna(mean_umur, inplace=True)
df['Gaji'].fillna(mean_gaji, inplace=True)

df

<ipython-input-9-3f09d7a429bc>:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Umur'].fillna(mean_umur, inplace=True)
<ipython-input-9-3f09d7a429bc>:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Gaji'].fillna(mean_gaji, inplace=True)

     Negara    Umur        Gaji Transaksi
0   Jakarta    44.0   8000000.0     Tidak
1   Bandung    27.0   6500000.0        Ya
2  Surabaya    30.0   4500000.0     Tidak
3   Bandung    38.0   7500000.0     Tidak
4  Surabaya    40.0   7674000.0        Ya
5   Jakarta    35.0  10000000.0        Ya
6   Bandung    38.0   8250000.0     Tidak
7   Jakarta    48.0   9750000.0        Ya
8  Surabaya  1000.0   7674000.0     Tidak
9   Jakarta    37.0   6700000.0        Ya

## Mengatasi Missing Values dengan Nilai Mode

## 5. Ganti Data Kosong (NaN) pada Umur dan Gaji dengan Nilai Modus

In [10]:
df = pd.read_csv('./Data.csv')
mean_umur = df['Umur'].mode()[0];
mean_gaji = df['Gaji'].mode()[0];

df['Umur'].fillna(mean_umur, inplace=True)
df['Gaji'].fillna(mean_gaji, inplace=True)

df

<ipython-input-10-2c203f330538>:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Umur'].fillna(mean_umur, inplace=True)
<ipython-input-10-2c203f330538>:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Gaji'].fillna(mean_gaji, inplace=True)

     Negara    Umur        Gaji Transaksi
0   Jakarta    44.0   8000000.0     Tidak
1   Bandung    27.0   6500000.0        Ya
2  Surabaya    30.0   4500000.0     Tidak
3   Bandung    38.0   7500000.0     Tidak
4  Surabaya    40.0   4500000.0        Ya
5   Jakarta    35.0  10000000.0        Ya
6   Bandung    27.0   8250000.0     Tidak
7   Jakarta    48.0   9750000.0        Ya
8  Surabaya  1000.0   7674000.0     Tidak
9   Jakarta    37.0   6700000.0        Ya

## Mengatasi Wrong Data dengan Ubah Data

## 6. Apabila Ada Umur yang diatas 120 maka ubah menjadi 33

In [11]:
df = pd.read_csv('./Data.csv')

for x in df.index:
    if df.loc[x, 'Umur'] > 120:
        df.loc[x, 'Umur'] = 33

df

     Negara  Umur        Gaji Transaksi
0   Jakarta  44.0   8000000.0     Tidak
1   Bandung  27.0   6500000.0        Ya
2  Surabaya  30.0   4500000.0     Tidak
3   Bandung  38.0   7500000.0     Tidak
4  Surabaya  40.0         NaN        Ya
5   Jakarta  35.0  10000000.0        Ya
6   Bandung   NaN   8250000.0     Tidak
7   Jakarta  48.0   9750000.0        Ya
8  Surabaya  33.0   7674000.0     Tidak
9   Jakarta  37.0   6700000.0        Ya

# PRAKTIKUM